[package]
name = "lspotify-player-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "lspotify-player-host"
path = "src/main.rs"

[dependencies]
lspotify-core = { path = "../lspotify-core" }
lspotify-platform = { path = "../lspotify-platform" }
gpui.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
