[package]
name = "lspotify-player-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "lspotify-player-host"
path = "src/main.rs"

[dependencies]
serde_json.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
gpui.workspace = true
lspotify-core = { path = "../lspotify-core" }
lspotify-platform = { path = "../lspotify-platform" }
serde.workspace = true

[lints]
workspace = true
