[package]
name = "mellowdeck"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mellowdeck-core = { path = "../mellowdeck-core" }
mellowdeck-platform = { path = "../mellowdeck-platform" }
mellowdeck-playback = { path = "../mellowdeck-playback" }
mellowdeck-spotify = { path = "../mellowdeck-spotify" }
mellowdeck-storage = { path = "../mellowdeck-storage" }
mellowdeck-ui = { path = "../mellowdeck-ui" }
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
