[package]
name = "mellowdeck-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
default-run = "featherspot"

[dependencies]
crossterm.workspace = true
mellowdeck-core = { path = "../mellowdeck-core" }
mellowdeck-platform = { path = "../mellowdeck-platform" }
mellowdeck-spotify = { path = "../mellowdeck-spotify" }
mellowdeck-storage = { path = "../mellowdeck-storage" }
ratatui.workspace = true
ratatui-image.workspace = true
image.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true


[lints]
workspace = true
