[package]
name = "mellowdeck-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mellowdeck-core = { path = "../mellowdeck-core" }

[target.'cfg(target_os = "windows")'.dependencies]
futures-channel.workspace = true
gpui.workspace = true
gpui_http_client.workspace = true
reqwest.workspace = true

[lints]
workspace = true
